### PR TITLE
[MGDOBR-397] Adjust integration tests

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

[Insert JIRA Issue number and update link](https://issues.redhat.com/browse/MGDOBR-)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@sutaakar Are you sure this is the correct fix?

Endpoints have always been `host/events` but were published on the Bridges API incorrectly as `host`.

Now the endpoint returned by the Bridges API includes the `/events` context so it does not feel right removing it in the tests.

Surely the tests should be getting the endpoint from the Bridges API and calling it directly: not adding of `/events`/ and [not removing](https://github.com/manstis/sandbox/pull/1/files#diff-1ff6f272758510613899db5e59da1d4f8a34ea9682d07b70c12a4cdbdc397d5cR56) it (from what was returned by the Bridges API).

**Comment by sutaakar** [comment]
The context is removed just for the cases when we need "plain" base URL for Bridge. The reason is that such endpoint is used to retrieve metrics, which are published on `/q/metrics` endpoint, for that we need to remove `/events`

**Comment by sutaakar** [comment]
For all other tests we leverage the URL returned by Bridges API (adding `/plain` for plain CE requests).

**Comment by manstis** [comment]
Thank-you @sutaakar

**Pull request merged**
